name: CycleGAN
channels:
- pytorch
- nvidia
- defaults
dependencies:
- python=3.8
- pytorch>=2.0.0
- torchvision
- pytorch-cuda=11.7
- scipy
- pip
- pip:
  - lpips
  - dominate==2.6.0
  - Pillow==8.0.1
  - numpy==1.19.2
  - visdom==0.1.8
  - wandb==0.12.18
